#!/bin/bash
set -e
set -u

echo -e "\e[32mCaDE Installation Script\e[0m"

sudo pacman -Syu hyprland
sudo pacman -Syu waybar

echo "Creating backup..."
mv ~/.config/hypr/hyprland.conf ~/.config/hypr/hyprland.conf.bak
mv ~/.config/waybar/config.jsonc ~/.config/waybar/config.jsonc.bak
mv ~/.config/waybar/style.css ~/.config/waybar/style.css.bak

echo "Creating CaDE Wallpapers configuration folder..."
mkdir -p ~/.config/cade
echo "Installing wallpaper... Mirror: https://images.hdqwalls.com/"
wget -P ~/.config/cade https://images.hdqwalls.com/wallpapers/bthumb/anime-girl-surrounded-by-butterflies-9t.jpg

echo "Setting up CaDE..."
cp hyprland.conf ~/.config/hypr/
cp waybar/config.jsonc ~/.config/waybar/
cp waybar/style.css ~/.config/waybar/
